/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import mensagem.Cliente;
import mensagem.CustomListModel;
import mensagem.ServidorChatInterface;
import java.rmi.Naming;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import mensagem.SimpleCrypto;

/**
 *
 * @author Scaketti
 */
public class TelaCliente extends javax.swing.JFrame {

    Cliente cliente = new Cliente(this);
    CustomListModel list_model = new CustomListModel();
    ArrayList<Cliente> clientesConectados = new ArrayList();

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();
        listClientes.setModel(list_model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConexao = new javax.swing.JLabel();
        btnServidor = new javax.swing.JButton();
        btnApelido = new javax.swing.JButton();
        txtMsgEnviar = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        lblNomeCliente = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMsgs = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLogCliente = new javax.swing.JTextArea();
        txtCliente = new javax.swing.JTextField();
        pnlClienteConectados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listClientes = new javax.swing.JList<>();
        lblLog = new javax.swing.JLabel();
        txtPortaServidor = new javax.swing.JTextField();
        txtServidor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblConexao.setText("Conectado ao servidor:");

        btnServidor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_server_lightning_36421 (1).png"))); // NOI18N
        btnServidor.setEnabled(false);
        btnServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServidorActionPerformed(evt);
            }
        });

        btnApelido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/if_client_account_template_64002.png"))); // NOI18N
        btnApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApelidoActionPerformed(evt);
            }
        });

        txtMsgEnviar.setEnabled(false);

        btnEnviar.setText("Enviar");
        btnEnviar.setEnabled(false);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        lblNomeCliente.setText("Cliente:");

        txtMsgs.setColumns(20);
        txtMsgs.setRows(5);
        txtMsgs.setEnabled(false);
        jScrollPane2.setViewportView(txtMsgs);

        txtLogCliente.setColumns(20);
        txtLogCliente.setRows(5);
        txtLogCliente.setEnabled(false);
        jScrollPane3.setViewportView(txtLogCliente);

        txtCliente.setEnabled(false);

        pnlClienteConectados.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes conectados"));

        listClientes.setEnabled(false);
        listClientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listClientesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listClientes);

        javax.swing.GroupLayout pnlClienteConectadosLayout = new javax.swing.GroupLayout(pnlClienteConectados);
        pnlClienteConectados.setLayout(pnlClienteConectadosLayout);
        pnlClienteConectadosLayout.setHorizontalGroup(
            pnlClienteConectadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteConectadosLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        pnlClienteConectadosLayout.setVerticalGroup(
            pnlClienteConectadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClienteConectadosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblLog.setText("Log:");

        txtPortaServidor.setEnabled(false);

        txtServidor.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNomeCliente)
                                .addGap(5, 5, 5)
                                .addComponent(txtCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblConexao)
                                .addGap(5, 5, 5)
                                .addComponent(txtServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPortaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(btnServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMsgEnviar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLog)
                            .addComponent(pnlClienteConectados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblNomeCliente)
                                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnApelido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnServidor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMsgEnviar)
                            .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblConexao)
                                .addComponent(txtPortaServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pnlClienteConectados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addComponent(lblLog)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServidorActionPerformed
        ConfigServidor configServ = new ConfigServidor(this, cliente, getTxtServidor().getText(), getTxtPortaServidor().getText());
        configServ.setVisible(true);
    }//GEN-LAST:event_btnServidorActionPerformed

    private void btnApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApelidoActionPerformed
        ConfigCliente configC = new ConfigCliente(this, cliente);
        configC.setVisible(true);
    }//GEN-LAST:event_btnApelidoActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        //Carrega o ip e porta do servidor que está conectado
        String ipServidor = txtServidor.getText();
        String portaServidor = txtPortaServidor.getText();

        //Tenta enviar a mensagem para o servidor encaminhar ao outro cliente
        try {
            ServidorChatInterface servidor = (ServidorChatInterface) Naming.lookup("rmi://" + ipServidor + ":" + portaServidor + "/chat");

            //Encripta a mensagem e salva como uma string
            String msgCriptografada = SimpleCrypto.encrypt(getTxtMsgEnviar().getText());

            //Envia a mensagem ao servidor
            int validacao = servidor.receberMensagemCliente(cliente.getApelido(), getListClientes().getSelectedValue(), msgCriptografada);

            if (validacao == 0) { //Caso a mensagem foi recebida
                for (Cliente c : clientesConectados) { //Pesquisa o cliente selecionado no array
                    if (c.getApelido().equals(getListClientes().getSelectedValue())) { //Ao encontrar, altera os valores do log de mensagens
                        c.setLogMensagens(c.getLogMensagens() + "\nVocê: " + getTxtMsgEnviar().getText());
                        txtMsgs.setText(c.getLogMensagens());
                    }
                }
            } else { //Caso a mensagem não foi recebida
                JOptionPane.showMessageDialog(null, "Não foi possível enviar a mensagem");
            }

            getTxtMsgEnviar().setText("");
        } catch (Exception e) {
            System.out.println("Erro: Mensagem: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void listClientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listClientesValueChanged
        //Selecionando qual cliente o usuário deseja ver as mensagens
        for (Cliente c : clientesConectados) { //Pesquisa o cliente no array de objetos
            if (c.getApelido().equals(getListClientes().getSelectedValue())) { //Quando encontrar atualizar a tela
                txtMsgs.setText(c.getLogMensagens());
                break;
            }
        }
    }//GEN-LAST:event_listClientesValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApelido;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnServidor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblConexao;
    private javax.swing.JLabel lblLog;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JList<String> listClientes;
    private javax.swing.JPanel pnlClienteConectados;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextArea txtLogCliente;
    private javax.swing.JTextField txtMsgEnviar;
    private javax.swing.JTextArea txtMsgs;
    private javax.swing.JTextField txtPortaServidor;
    private javax.swing.JTextField txtServidor;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the txtLogCliente
     */
    public javax.swing.JTextArea getTxtLogCliente() {
        return txtLogCliente;
    }

    /**
     * @param txtLogCliente the txtLogCliente to set
     */
    public void setTxtLogCliente(javax.swing.JTextArea txtLogCliente) {
        this.txtLogCliente = txtLogCliente;
    }

    public void retornaCliente(Cliente cliente) {
        this.cliente = cliente;
        getTxtCliente().setText(cliente.getNome());
    }

    /**
     * @return the txtMsgs
     */
    public javax.swing.JTextArea getTxtMsgs() {
        return txtMsgs;
    }

    /**
     * @param txtMsgs the txtMsgs to set
     */
    public void setTxtMsgs(javax.swing.JTextArea txtMsgs) {
        this.txtMsgs = txtMsgs;
    }

    public void insereClienteLista(String apelido) {
        Cliente c = new Cliente(null);
        c.setApelido(apelido);
        getTxtLogCliente().append("Cliente: " + c.getApelido() + " está conectado ao servidor.\n");
        clientesConectados.add(c);
        list_model.addCliente(c);
    }

    public void atualizaMensagemCliente(String apelido, String mensagem) {
        for (Cliente c : clientesConectados) { //Pesquiso o cliente respectivo para atualizar seu log de mensagens
            if (c.getApelido().equals(apelido)) {
                c.setLogMensagens(c.getLogMensagens() + "\n" + apelido + ": " + mensagem);
                if (listClientes.getSelectedValue().equals(apelido)) {
                    txtMsgs.append("\n" + apelido + ": " + mensagem); //Se o usuário enviar uma mensagem e ele ja estiver selecionado, atualiza na tela
                }
            }
        }
    }

    public void removeClienteLista(String apelido) {
        for (Cliente c : clientesConectados) { //Pesquisa o cliente com o nome a ser desconectado
            if (c.getApelido().equals(apelido)) {
                for (int i = 0; i <= list_model.getSize(); i++) { //Pesquisa no list_model o cliente
                    if (c == list_model.getCliente(i)) { //Se o cliente no array for igual ao cliente no list_model, então remove
                        getTxtLogCliente().append("Cliente " + apelido + " se desconectou.\n");
                        clientesConectados.remove(c);
                        list_model.removeCliente(i);
                    }
                }
            }
        }
    }

    public void removeAllListaCliente() {
        clientesConectados.removeAll(clientesConectados);
        list_model.removeAll();
    }

    public void atualizaDadosServidor(String ip, String porta) {
        txtServidor.setText(ip);
        txtPortaServidor.setText(porta);
    }

    public void atualizaTelaConectaDesconecta(boolean acao) {
        btnApelido.setEnabled(!acao);
        txtMsgEnviar.setEnabled(acao);
        listClientes.setEnabled(acao);
        btnEnviar.setEnabled(acao);
        txtLogCliente.setText("");
        txtMsgs.setText("");
    }

    /**
     * @return the txtServidor
     */
    public javax.swing.JTextField getTxtServidor() {
        return txtServidor;
    }

    /**
     * @param txtServidor the txtServidor to set
     */
    public void setTxtServidor(javax.swing.JTextField txtServidor) {
        this.txtServidor = txtServidor;
    }

    /**
     * @return the txtPortaServidor
     */
    public javax.swing.JTextField getTxtPortaServidor() {
        return txtPortaServidor;
    }

    /**
     * @param txtPortaServidor the txtPortaServidor to set
     */
    public void setTxtPortaServidor(javax.swing.JTextField txtPortaServidor) {
        this.txtPortaServidor = txtPortaServidor;
    }

    /**
     * @return the btnServidor
     */
    public javax.swing.JButton getBtnServidor() {
        return btnServidor;
    }

    /**
     * @param btnServidor the btnServidor to set
     */
    public void setBtnServidor(javax.swing.JButton btnServidor) {
        this.btnServidor = btnServidor;
    }

    /**
     * @return the btnApelido
     */
    public javax.swing.JButton getBtnApelido() {
        return btnApelido;
    }

    /**
     * @param btnApelido the btnApelido to set
     */
    public void setBtnApelido(javax.swing.JButton btnApelido) {
        this.btnApelido = btnApelido;
    }

    /**
     * @return the txtCliente
     */
    public javax.swing.JTextField getTxtCliente() {
        return txtCliente;
    }

    /**
     * @param txtCliente the txtCliente to set
     */
    public void setTxtCliente(javax.swing.JTextField txtCliente) {
        this.txtCliente = txtCliente;
    }

    /**
     * @return the txtMsgEnviar
     */
    public javax.swing.JTextField getTxtMsgEnviar() {
        return txtMsgEnviar;
    }

    /**
     * @param txtMsgEnviar the txtMsgEnviar to set
     */
    public void setTxtMsgEnviar(javax.swing.JTextField txtMsgEnviar) {
        this.txtMsgEnviar = txtMsgEnviar;
    }

    /**
     * @return the listClientes
     */
    public javax.swing.JList<String> getListClientes() {
        return listClientes;
    }

    /**
     * @param listClientes the listClientes to set
     */
    public void setListClientes(javax.swing.JList<String> listClientes) {
        this.listClientes = listClientes;
    }

    /**
     * @return the btnEnviar
     */
    public javax.swing.JButton getBtnEnviar() {
        return btnEnviar;
    }

    /**
     * @param btnEnviar the btnEnviar to set
     */
    public void setBtnEnviar(javax.swing.JButton btnEnviar) {
        this.btnEnviar = btnEnviar;
    }
}
